"""created lesson table

Revision ID: 5af9a6c9d7bd
Revises: 46ce863a4088
Create Date: 2025-06-28 09:58:43.954810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af9a6c9d7bd'
down_revision = '46ce863a4088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lessonName', sa.String(length=255), nullable=False),
    sa.Column('cmd', sa.String(length=255), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    # ### end Alembic commands ###
